### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by refi64** [0intro/libregexp#1]
Does this work on Windows? I didn't quite see anything Posix-specific in the source, but I want to make sure.

**Comment by 0intro** [comment]
Yes, it should work on Windows.
You can cross-compile it with MinGW by setting the GCC variable in the Makefile.
Also, you might want to add a rule in the Makefile to generate a DLL.

**Comment by refi64** [comment]
@0intro Well, I'd likely just be embedding the whole thing and re-building myself, so it's perfectly fine as-is. Thanks!
